[[navbar]]
  identifier = "setup"
  name = "Setup"
  url = "/setup/"
  weight = 1

[[navbar]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 6
[[navbar]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 7
[[navbar]]
  identifier = "cv"
  name = "CV"
  url = "/cv/"
  weight = 8
