[[navbar]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 1
[[navbar]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2
# [[navbar]]
#   identifier = "cv"
#   name = "CV"
#   url = "/cv/"
#   weight = 3
[[navbar]]
  identifier = "moments"
  name = "Moments"
  url = "/moments/"
  weight = 4

